version: "3.2"

services:
  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    #working_dir: /frontend/name_project
    command: ng serve --host 0.0.0.0 --port 4201
    ports:
      - "8000:4201"