version: "3.2"

services:
  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend/multasapp
    command: ng serve
    ports:
     - 4200:4200
